name: Theme Builder

on: [push]

jobs:
  test-workflow-runner:
    runs-on: ubuntu-22.04
    steps:
      - name: Report Running
        run: |
          echo "Test Workflow Runner is Working."
          node -v
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Packages
        run: npm install
      - name: Build Style Dictionary
        run: npx style-dictionary build
      - name: "Get Previous tag"
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.previous_tag.outputs.tag}}
          files: ./build/**/*
